### ISSUE TITLE
[bugfix/25_06_2018] OMC193 - Trang View Purchase Order, View Quotation, View Return Request  xuất hiện ký tự khác

### ISSUE THREAD

**Issue by davidmagestore** [Magestore/SupplierSuccess#12]
1.Go to backend: https://omc-hotfix.magestore.com/admin >Purchase Management> create purchase>>Prepare Product List
Actual result:
Trên trang view purchase xuất hiện ký tự khác ở dưới tên supplier"
Kỹ tự này show ra ở đúng chỗ của address. Nhưng trong trường hợp này mình đang không chọn address mà nó tự show ra một cái "State" ở chỗ này.

**Comment by davidmagestore** [comment]
From [PurchaseOrderSuccess issue #11](https://github.com/Magestore/PurchaseOrderSuccess-M2/issues/11)

**Comment by davidmagestore** [comment]
Vì data bị sai thì hiển thị cũng sai. Nên chỉ cần Fix để dữ liệu đúng là được.

Dữ liệu sai vì phần JS tự nhận default sai => fix default

**Comment by davidmagestore** [comment]
Đã Test:
- Thêm, Sửa Supplier trong Admin > Vào xem Purchase Order, Quotation, thấy không hiển thị kí tự lạ nữa

Tôi đảm bảo tính năng này không làm ảnh hưởng đến các tính năng khác

**Comment by laptc** [comment]
Đã test done trên CE 223
- Test trường hợp supplier mới có address
- Test trường hợp supplier mới không có address
- Test trường hợp supplier cũ (lỗi trước khi apply patch fix)
